# Generated by Django 2.1.3 on 2018-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
