# Generated by Django 2.1.3 on 2018-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='img',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
