# Generated by Django 2.1.3 on 2018-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
