# Generated by Django 2.1.3 on 2018-11-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20181123_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
