# Generated by Django 2.1.3 on 2018-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20181123_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
