# Generated by Django 2.1.3 on 2018-11-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20181123_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
