# Generated by Django 2.1.3 on 2018-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20181204_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaire',
            name='id',
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='email',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
